name: gofmt

on:
  push:
    branches:
      - '*-test'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'enhancements/**'
      - '*.md'

jobs:
  gofmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run gofmt test
        run: ./automation/presubmit-tests/gofmt.sh