name: go vulnerability detect

on:
  push:
    branches:
      - '*-test'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'enhancements/**'
      - '*.md'

jobs:
  vulnerability_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run vulnerability detect
        run: make govulncheck