name: image

on:
  push:
    branches: 
    - main
    - model-server-build
    paths-ignore:
      - 'doc/**'
      - 'enhancements/**'
      - '*.md'

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GH
      uses: docker/login-action@v1
      with:
        registry: ghcr.io/sunya-ch
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push kepler latest
      uses: docker/build-push-action@v4
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/sunya-ch/kepler:latest
          labels: latest
          file: build/Dockerfile

    - name: Build and push kepler latest (libbpf)
      uses: docker/build-push-action@v4
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/sunya-ch/kepler:latest-libbpf
          labels: latest-libbpf
          file: build/Dockerfile.libbpf.kepler