name: Makefile and Test

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - name: Debug
      run: |
        go env
    - name: Get ginkgo
      run: make ginkgo-set
      env:
        GOPATH: /home/runner/go
        GOBIN: /home/runner/go/bin
    - name: Run 
      run: make test
